name:                symbolic-tophat
version:             0.1.0.0
# synopsis:
description:         Please see the README on GitHub at <https://github.com/timjs/symbolic-tophat#readme>
github:              "timjs/symbolic-tophat"
license:             BSD3
author:              "Tim Steenvoorden"
maintainer:          "tim.steenvoorden@me.com"
copyright:           "BSD3"
# category:            Web


extra-source-files:
  - README.md


dependencies:
  - base-noprelude >= 4.12 && < 5
  - relude >= 0.5 && < 1
  - mtl
  - text
  - vector
  - prettyprinter
  - Stream
  - containers
  - unordered-containers
  - sbv >= 8.0 && < 9


default-extensions:
  # Lifting limitations:
  - EmptyDataDecls
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses

  # Syntactic conveniences:
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - NumericUnderscores

  # Deriving:
  - DeriveGeneric
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  # - GeneralizedNewtypeDeriving
  - DerivingVia
  # - StandaloneDeriving

  # Syntactic adjustments:
  - BangPatterns
  - KindSignatures
  - TypeOperators
  - MonadComprehensions
  - BinaryLiterals
  - NegativeLiterals
  - NoStarIsType
  - BlockArguments

  # Type annotations:
  - ScopedTypeVariables
  - TypeApplications
  - PartialTypeSignatures
  - NamedWildCards

  # Prelude and overloading:
  # - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLists

  # Type extensions:
  - ConstraintKinds
  - RankNTypes

  # Intermediate syntactic adjustments:
  - DefaultSignatures
  - PatternSynonyms
  - PatternGuards
  # - ApplicativeDo

  # Intermediate type extensions:
  - FunctionalDependencies
  # - UndecidableInstances
  - GADTs
  - ExistentialQuantification

  # Advanced type extensions:
  - DataKinds
  - PolyKinds
  - TypeFamilies
  # - TypeFamilyDependencies
  - QuantifiedConstraints


ghc-options:

  - -Wall
  - -Wcompat

  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -Wno-deprecations
  - -Wno-missing-pattern-synonym-signatures

  # - -Weverything
  # - -Wno-safe
  # - -Wno-unsafe
  # - -Wno-implicit-prelude


library:
  source-dirs: src


executable:
  main:                Main.hs
  source-dirs:         src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
  - symbolic-tophat
